/**
 * English → Korean team name mapping.
 * Reverse of backend/src/services/teamMatcher.js TEAM_NAME_MAP.
 * 중복 매핑 시 가장 일반적인(짧은) 한국어 이름을 대표값으로 선택.
 */
const ENGLISH_TO_KOREAN: Record<string, string> = {
  // ─── EPL ───
  'Manchester City': '맨시티',
  'Manchester United': '맨유',
  'Liverpool': '리버풀',
  'Arsenal': '아스널',
  'Chelsea': '첼시',
  'Tottenham Hotspur': '토트넘',
  'Newcastle United': '뉴캐슬',
  'Brighton and Hove Albion': '브라이튼',
  'Aston Villa': '애스턴빌라',
  'West Ham United': '웨스트햄',
  'AFC Bournemouth': '본머스',
  'Fulham FC': '풀럼',
  'Crystal Palace': '크리스탈팰리스',
  'Brentford': '브렌트포드',
  'Everton': '에버턴',
  'Wolverhampton Wanderers': '울버햄턴',
  'Nottingham Forest': '노팅엄',
  'Burnley': '번리',
  'Sheffield United': '셰필드유',
  'Luton Town': '루턴',
  'Ipswich Town': '입스위치',
  'Leicester City': '레스터',
  'Southampton': '사우샘프턴',
  'Sunderland': '선덜랜드',
  'Leeds United': '리즈U',

  // ─── La Liga ───
  'Barcelona': '바르셀로나',
  'Real Madrid': '레알마드리드',
  'Atletico Madrid': '아틀레티코',
  'Girona': '지로나',
  'Real Sociedad': '소시에다드',
  'Real Betis': '베티스',
  'Villarreal': '비야레알',
  'Valencia': '발렌시아',
  'Sevilla': '세비야',
  'Celta Vigo': '셀타비고',
  'Mallorca': '마요르카',
  'Las Palmas': '라스팔마스',
  'Osasuna': '오사수나',
  'Deportivo Alaves': '알라베스',
  'Cadiz': '카디스',
  'Granada': '그라나다',
  'Getafe': '헤타페',
  'Rayo Vallecano': '라요바예카노',
  'Espanyol': '에스파뇰',
  'Athletic Bilbao': '빌바오',
  'Elche': '엘체',
  'Real Oviedo': '오비에도',

  // ─── Bundesliga ───
  'Bayern Munich': '바이에른',
  'Borussia Dortmund': '도르트문트',
  'RB Leipzig': '라이프치히',
  'Bayer Leverkusen': '레버쿠젠',
  'Eintracht Frankfurt': '프랑크푸르트',
  'SC Freiburg': '프라이부르크',
  'Werder Bremen': '브레멘',
  'VfL Wolfsburg': '볼프스부르크',
  'TSG Hoffenheim': '호펜하임',
  'Borussia Monchengladbach': '묀헨글라드바흐',
  'VfB Stuttgart': '슈투트가르트',
  'Mainz 05': '마인츠',
  'FC Augsburg': '아우크스부르크',
  'FC Koln': '쾰른',
  'SV Darmstadt 98': '다름슈타트',
  'FC Heidenheim': '하이덴하임',
  'Union Berlin': '우니온베를린',
  'FC St. Pauli': '장크트파울리',
  'Hamburger SV': '함부르크',

  // ─── Serie A ───
  'Inter Milan': '인테르',
  'Juventus': '유벤투스',
  'AC Milan': '밀란',
  'Napoli': '나폴리',
  'AS Roma': '로마',
  'Lazio': '라치오',
  'Atalanta': '아탈란타',
  'Fiorentina': '피오렌티나',
  'Bologna': '볼로냐',
  'Torino': '토리노',
  'Sassuolo': '사수올로',
  'Hellas Verona': '엘라스',
  'Udinese': '우디네세',
  'Genoa': '제노아',
  'Cagliari': '칼리아리',
  'Como 1907': '코모1907',
  'US Lecce': '레체',
  'AC Pisa': '피사SC',
  'Parma': '파르마',

  // ─── Ligue 1 ───
  'Paris Saint Germain': 'PSG',
  'AS Monaco': '모나코',
  'Marseille': '마르세유',
  'Lille': '릴',
  'Lyon': '리옹',
  'Rennes': '렌',
  'Nice': '니스',
  'Strasbourg': '스트라스부르',
  'Toulouse': '툴루즈',
  'Montpellier': '몽펠리에',
  'Nantes': '낭트',
  'Angers': '앙제',
  'Le Havre': '르아브르',
  'Saint-Etienne': '생테티엔',
  'Brest': '브레스트',
  'Stade de Reims': '랭스',
  'Lorient': '로리앙',
  'Metz': '메스',
  'Auxerre': '오세르',
  'Paris FC': '파리FC',

  // ─── UCL / UEL / UECL ───
  'Galatasaray': '갈라타사라이',
  'Sporting CP': '스포르팅',
  'Besiktas': '베식타스',
  'Fenerbahce': '페네르바체',
  'FC Porto': '포르투',
  'Benfica': '벤피카',
  'Celtic': '셀틱FC',
  'Rangers': '레인저스',
  'Red Bull Salzburg': '살츠부르크',
  'Club Brugge': '클럽브뤼헤',
  'Ajax': '아약스',
  'PSV Eindhoven': 'PSV',
  'Feyenoord': '페예노르트',
  'Bodo/Glimt': '보되글림트',

  // ─── NBA ───
  'Los Angeles Lakers': '레이커스',
  'Boston Celtics': '셀틱스',
  'Denver Nuggets': '너겟츠',
  'Milwaukee Bucks': '밀워키',
  'Philadelphia 76ers': '식서즈',
  'Phoenix Suns': '선즈',
  'Golden State Warriors': '워리어스',
  'Los Angeles Clippers': '클리퍼스',
  'Miami Heat': '히트',
  'Dallas Mavericks': '매버릭스',
  'New York Knicks': '닉스',
  'Cleveland Cavaliers': '캐벌리어스',
  'Sacramento Kings': '킹스',
  'Memphis Grizzlies': '그리즐리스',
  'New Orleans Pelicans': '펠리컨스',
  'Minnesota Timberwolves': '팀버울브스',
  'Oklahoma City Thunder': '선더',
  'Portland Trail Blazers': '포틀랜드',
  'Toronto Raptors': '랩터스',
  'San Antonio Spurs': '스퍼스',
  'Utah Jazz': '재즈',
  'Chicago Bulls': '불스',
  'Atlanta Hawks': '호크스',
  'Washington Wizards': '위저즈',
  'Orlando Magic': '매직',
  'Detroit Pistons': '피스톤스',
  'Indiana Pacers': '페이서스',
  'Brooklyn Nets': '넷츠',
  'Charlotte Hornets': '호넷츠',
  'Houston Rockets': '로켓츠',

  // ─── KBL ───
  'Seoul Samsung Thunders': '서울삼성',
  'Anyang KGC': '안양정관',
  'Wonju DB Promy': '원주DB',
  'Seoul SK Knights': '서울SK',
  'Goyang Carrot Jumpers': '고양캐롯',
  'Busan KCC Egis': '부산KCC',
  'Changwon LG Sakers': '창원LG',
  'Daegu KOGAS Pegasus': '대구한국가스공사',
  'Suwon KT Sonicboom': '수원KT',
  'Ulsan Hyundai Mobis Phoebus': '울산현대모비스',

  // ─── A-League ───
  'Adelaide United': '애들레이드',
  'Wellington Phoenix': '웰링턴',
  'Melbourne City FC': '멜번시티',
  'Melbourne Victory': '멜번빅토리',
  'Sydney FC': '시드니FC',
  'Western United': '웨스턴유나이티드',
  'Central Coast Mariners': '센트럴코스트',
  'Brisbane Roar': '브리즈번',
  'Perth Glory': '퍼스글로리',
  'Macarthur FC': '맥아서FC',
  'Western Sydney Wanderers': '웨스턴시드니',
  'Newcastle Jets': '뉴캐슬제츠',
  'Auckland FC': '오클FC',

  // ─── Eredivisie ───
  'Heracles Almelo': '헤라클레스',
  'FC Utrecht': '위트레흐트',
  'AZ Alkmaar': '알크마르',
  'FC Twente': '트벤테',
  'FC Groningen': '흐로닝언',
  'NEC Nijmegen': '네이메헌',
  'Sparta Rotterdam': '스파르타R',
  'SC Heerenveen': '헤이렌베인',
  'PEC Zwolle': '즈볼러',
  'Fortuna Sittard': '포르투나S',
  'Go Ahead Eagles': '고어헤드',
  'Excelsior': '엑셀시오르',
  'FC Volendam': '폴렌담',
  'NAC Breda': '브레다',
  'Telstar': '텔스타',

  // ─── EFL Championship ───
  'Norwich City': '노리치',
  'Wrexham': '렉섬',
  'Middlesbrough': '미들즈브러',
  'Millwall': '밀월',
  'Birmingham City': '버밍엄',
  'Bristol City': '브리스톨',
  'Blackburn Rovers': '블랙번',
  'Sheffield Wednesday': '셰필드웬',
  'Swansea City': '스완지',
  'Stoke City': '스토크',
  'Oxford United': '옥스퍼드',
  'Watford': '왓포드',
  'West Bromwich Albion': '웨스트브롬',
  'Charlton Athletic': '찰턴',
  'Coventry City': '코번트리',
  'Queens Park Rangers': '퀸즈파크',
  'Preston North End': '프레스턴',
  'Hull City': '헐시티',

  // ─── MLS ───
  'Nashville SC': '내슈빌SC',
  'New York Red Bulls': '뉴욕레드불스',
  'New York City FC': '뉴욕시티FC',
  'New England Revolution': '뉴잉글랜드',
  'Real Salt Lake': '레알솔트레이크',
  'Minnesota United': '미네소타유나이티드',
  'Vancouver Whitecaps': '밴쿠버',
  'San Jose Earthquakes': '새너제이',
  'San Diego FC': '샌디에고FC',
  'Charlotte FC': '샬럿FC',
  'St. Louis City SC': '세인트루이스',
  'Seattle Sounders': '시애틀',
  'Chicago Fire': '시카고파이어',
  'Atlanta United': '애틀랜타유나이티드',
  'Austin FC': '오스틴FC',
  'Orlando City': '올랜도시티',
  'Inter Miami': '인터마이애미',
  'Columbus Crew': '콜럼버스',
  'Colorado Rapids': '콜로라도',
  'Toronto FC': '토론토FC',
  'Portland Timbers': '포틀랜드팀버스',
  'Philadelphia Union': '필라델피아유니온',
  'Houston Dynamo': '휴스턴다이나모',
  'CF Montreal': '몬트리올',
  'DC United': 'DC유나이티드',
  'FC Dallas': 'FC댈러스',
  'FC Cincinnati': 'FC신시내티',
  'LA Galaxy': 'LA갤럭시',
  'Los Angeles FC': 'LAFC',
  'Sporting Kansas City': '스포르팅KC',
};

/**
 * 영어 팀 이름을 한국어로 변환.
 * 매핑에 없으면 원래 이름 그대로 반환.
 */
export function getKoreanTeamName(englishName: string): string {
  if (!englishName) return englishName;
  return ENGLISH_TO_KOREAN[englishName] ?? englishName;
}
