/**
 * English → Korean team name mapping.
 * 중복 매핑 시 가장 일반적인(짧은) 한국어 이름을 대표값으로 선택.
 */
const ENGLISH_TO_KOREAN: Record<string, string> = {
  // ─── EPL ───
  'Manchester City': '맨시티',
  'Manchester United': '맨유',
  'Liverpool': '리버풀',
  'Arsenal': '아스널',
  'Arsenal FC': '아스널',
  'Chelsea': '첼시',
  'Chelsea FC': '첼시',
  'Tottenham Hotspur': '토트넘',
  'Tottenham': '토트넘',
  'Newcastle United': '뉴캐슬',
  'Brighton and Hove Albion': '브라이튼',
  'Brighton & Hove Albion': '브라이튼',
  'Brighton': '브라이튼',
  'Aston Villa': '애스턴빌라',
  'West Ham United': '웨스트햄',
  'AFC Bournemouth': '본머스',
  'Bournemouth': '본머스',
  'Fulham FC': '풀럼',
  'Fulham': '풀럼',
  'Crystal Palace': '크리스탈팰리스',
  'Brentford': '브렌트포드',
  'Brentford FC': '브렌트포드',
  'Everton': '에버턴',
  'Everton FC': '에버턴',
  'Wolverhampton Wanderers': '울버햄턴',
  'Wolverhampton': '울버햄턴',
  'Nottingham Forest': '노팅엄',
  'Burnley': '번리',
  'Burnley FC': '번리',
  'Sheffield United': '셰필드유',
  'Sheffield United FC': '셰필드유',
  'Luton Town': '루턴',
  'Ipswich Town': '입스위치',
  'Leicester City': '레스터',
  'Leicester City FC': '레스터',
  'Southampton': '사우샘프턴',
  'Southampton FC': '사우샘프턴',
  'Sunderland': '선덜랜드',
  'Sunderland AFC': '선덜랜드',
  'Leeds United': '리즈U',

  // ─── La Liga ───
  'Barcelona': '바르셀로나',
  'FC Barcelona': '바르셀로나',
  'Real Madrid': '레알마드리드',
  'Atletico Madrid': '아틀레티코',
  'Atlético Madrid': '아틀레티코',
  'Girona': '지로나',
  'Girona FC': '지로나',
  'Real Sociedad': '소시에다드',
  'Real Betis': '베티스',
  'Villarreal': '비야레알',
  'Villareal': '비야레알',
  'Valencia': '발렌시아',
  'Valencia CF': '발렌시아',
  'Sevilla': '세비야',
  'Sevilla FC': '세비야',
  'Celta Vigo': '셀타비고',
  'RC Celta': '셀타비고',
  'Mallorca': '마요르카',
  'RCD Mallorca': '마요르카',
  'Las Palmas': '라스팔마스',
  'UD Las Palmas': '라스팔마스',
  'Osasuna': '오사수나',
  'CA Osasuna': '오사수나',
  'Deportivo Alaves': '알라베스',
  'Alavés': '알라베스',
  'Cadiz': '카디스',
  'Cadiz CF': '카디스',
  'Granada': '그라나다',
  'Granada CF': '그라나다',
  'Getafe': '헤타페',
  'Getafe CF': '헤타페',
  'Rayo Vallecano': '라요바예카노',
  'Espanyol': '에스파뇰',
  'RCD Espanyol': '에스파뇰',
  'Athletic Bilbao': '빌바오',
  'Athletic Club': '빌바오',
  'Elche': '엘체',
  'Real Oviedo': '오비에도',
  'Oviedo': '오비에도',
  'Levante': '레반테',
  'Levante UD': '레반테',
  'Real Valladolid': '바야돌리드',
  'CD Leganes': '레가네스',
  'Leganes': '레가네스',
  'Real Zaragoza': '사라고사',

  // ─── Bundesliga ───
  'Bayern Munich': '바이에른',
  'Red Bull Munich': '바이에른',
  'Borussia Dortmund': '도르트문트',
  'RB Leipzig': '라이프치히',
  'Bayer Leverkusen': '레버쿠젠',
  'Eintracht Frankfurt': '프랑크푸르트',
  'SC Freiburg': '프라이부르크',
  'Freiburg': '프라이부르크',
  'Werder Bremen': '브레멘',
  'VfL Wolfsburg': '볼프스부르크',
  'VFL Wolfsburg': '볼프스부르크',
  'Wolfsburg': '볼프스부르크',
  'TSG Hoffenheim': '호펜하임',
  'Hoffenheim': '호펜하임',
  'Borussia Monchengladbach': '묀헨글라드바흐',
  'VfB Stuttgart': '슈투트가르트',
  'Mainz 05': '마인츠',
  'FSV Mainz': '마인츠',
  'FSV Mainz 05': '마인츠',
  'Mainz': '마인츠',
  'FC Augsburg': '아우크스부르크',
  'Augsburg': '아우크스부르크',
  'FC Koln': '쾰른',
  '1. FC Koln': '쾰른',
  '1. FC Köln': '쾰른',
  '1. FC Cologne': '쾰른',
  'SV Darmstadt 98': '다름슈타트',
  'FC Heidenheim': '하이덴하임',
  '1. FC Heidenheim': '하이덴하임',
  'Heidenheim': '하이덴하임',
  'Union Berlin': '우니온베를린',
  'FC St. Pauli': '장크트파울리',
  'St. Pauli': '장크트파울리',
  'Hamburger SV': '함부르크',
  'Holstein Kiel': '홀슈타인킬',

  // ─── Serie A ───
  'Inter Milan': '인테르',
  'FC Internazionale': '인테르',
  'Juventus': '유벤투스',
  'Juventus FC': '유벤투스',
  'AC Milan': '밀란',
  'Napoli': '나폴리',
  'SSC Napoli': '나폴리',
  'AS Roma': '로마',
  'Roma': '로마',
  'Lazio': '라치오',
  'SS Lazio': '라치오',
  'Atalanta': '아탈란타',
  'Atalanta BC': '아탈란타',
  'Fiorentina': '피오렌티나',
  'ACF Fiorentina': '피오렌티나',
  'Bologna': '볼로냐',
  'Bologna FC': '볼로냐',
  'Torino': '토리노',
  'Torino FC': '토리노',
  'Sassuolo': '사수올로',
  'Hellas Verona': '엘라스베로나',
  'Udinese': '우디네세',
  'Udinese Calcio': '우디네세',
  'Genoa': '제노아',
  'Genoa CFC': '제노아',
  'Cagliari': '칼리아리',
  'Cagliari Calcio': '칼리아리',
  'Como 1907': '코모',
  'Como': '코모',
  'US Lecce': '레체',
  'Lecce': '레체',
  'AC Pisa': '피사',
  'Pisa': '피사',
  'Pisa SC': '피사',
  'Parma': '파르마',
  'Parma Calcio': '파르마',
  'Monza': '몬차',
  'AC Monza': '몬차',
  'Empoli': '엠폴리',
  'Empoli FC': '엠폴리',
  'Venezia FC': '베네치아',
  'Venezia': '베네치아',
  'Sampdoria': '삼프도리아',
  'Salernitana': '살레르니타나',
  'Spezia': '스페치아',
  'Frosinone': '프로시노네',
  'Cremonese': '크레모네세',

  // ─── Ligue 1 ───
  'Paris Saint Germain': 'PSG',
  'Paris Saint-Germain': 'PSG',
  'Paris Saint-Germain FC': 'PSG',
  'PSG': 'PSG',
  'AS Monaco': '모나코',
  'Monaco': '모나코',
  'Marseille': '마르세유',
  'Olympique Marseille': '마르세유',
  'Olympique de Marseille': '마르세유',
  'Lille': '릴',
  'Lille OSC': '릴',
  'Lyon': '리옹',
  'Olympique Lyon': '리옹',
  'Olympique Lyonnais': '리옹',
  'Rennes': '렌',
  'Stade Rennais': '렌',
  'Nice': '니스',
  'OGC Nice': '니스',
  'Strasbourg': '스트라스부르',
  'RC Strasbourg': '스트라스부르',
  'Toulouse': '툴루즈',
  'Toulouse FC': '툴루즈',
  'Montpellier': '몽펠리에',
  'Montpellier HSC': '몽펠리에',
  'Nantes': '낭트',
  'FC Nantes': '낭트',
  'Angers': '앙제',
  'Angers SCO': '앙제',
  'Le Havre': '르아브르',
  'Le Havre AC': '르아브르',
  'Saint-Etienne': '생테티엔',
  'AS Saint-Etienne': '생테티엔',
  'Brest': '브레스트',
  'Stade Brestois': '브레스트',
  'Stade de Reims': '랭스',
  'RC Lens': '랑스',
  'Lens': '랑스',
  'Lorient': '로리앙',
  'FC Lorient': '로리앙',
  'Metz': '메스',
  'FC Metz': '메스',
  'Auxerre': '오세르',
  'AJ Auxerre': '오세르',
  'Paris FC': '파리FC',

  // ─── UCL / UEL / UECL ───
  'Galatasaray': '갈라타사라이',
  'Galatasaray Istanbul': '갈라타사라이',
  'Sporting CP': '스포르팅',
  'Sporting Lisbon': '스포르팅',
  'Besiktas': '베식타스',
  'Fenerbahce': '페네르바체',
  'FC Porto': '포르투',
  'Porto': '포르투',
  'Benfica': '벤피카',
  'SL Benfica': '벤피카',
  'Celtic': '셀틱',
  'Celtic FC': '셀틱',
  'Rangers': '레인저스',
  'Rangers FC': '레인저스',
  'Red Bull Salzburg': '살츠부르크',
  'FC Salzburg': '살츠부르크',
  'Club Brugge': '클럽브뤼헤',
  'Club Brugge KV': '클럽브뤼헤',
  'Ajax': '아약스',
  'AFC Ajax': '아약스',
  'PSV Eindhoven': 'PSV',
  'PSV': 'PSV',
  'Feyenoord': '페예노르트',
  'Feyenoord Rotterdam': '페예노르트',
  'Bodo/Glimt': '보되글림트',
  'Bodoe/Glimt': '보되글림트',
  'Bodø/Glimt': '보되글림트',
  'AEK Athens': 'AEK아테네',
  'AEK Athens FC': 'AEK아테네',
  'Olympiacos': '올림피아코스',
  'Olympiacos FC': '올림피아코스',
  'Panathinaikos': '파나티나이코스',
  'Panathinaikos BC': '파나티나이코스',
  'FC Shakhtar Donetsk': '샤흐타르',
  'Shakhtar Donetsk': '샤흐타르',
  'Ferencvarosi TC': '페렌츠바로시',
  'Ferencvaros': '페렌츠바로시',
  'Dinamo Zagreb': '디나모자그레브',
  'GNK Dinamo Zagreb': '디나모자그레브',
  'Slavia Prague': '슬라비아프라하',
  'Sparta Prague': '스파르타프라하',
  'Young Boys': '영보이즈',
  'BSC Young Boys': '영보이즈',
  'FC Copenhagen': '코펜하겐',
  'Braga': '브라가',
  'SC Braga': '브라가',
  'Anderlecht': '안데를레흐트',
  'RSC Anderlecht': '안데를레흐트',
  'Standard Liege': '스탕다르',
  'FC Bruges': '클럽브뤼헤',
  'Lille Osc': '릴',
  'FC Midtjylland': '미트윌란',
  'Lask Linz': 'LASK',
  'LASK': 'LASK',
  'Sturm Graz': '슈투름그라츠',
  'SK Sturm Graz': '슈투름그라츠',

  // ─── Primeira Liga (Portugal) ───
  'SC Farense': '파렌세',
  'Vitoria de Guimaraes': '비토리아기마랑이스',
  'Vitoria SC': '비토리아기마랑이스',
  'CD Santa Clara': '산타클라라',
  'Gil Vicente': '질비센테',
  'Rio Ave': '리우아베',
  'Moreirense': '모레이렌세',
  'Estoril Praia': '에스토릴',
  'CF Estrela Amadora': '에스트렐라',
  'Boavista': '보아비스타',
  'Casa Pia AC': '카사피아',
  'Famalicao': '파말리캉',
  'Nacional': '나시오날',
  'AVS Futebol SAD': 'AVS',
  'Arouca': '아로우카',

  // ─── NBA ───
  'Los Angeles Lakers': '레이커스',
  'LA Lakers': '레이커스',
  'Boston Celtics': '셀틱스',
  'Denver Nuggets': '너겟츠',
  'Milwaukee Bucks': '밀워키',
  'Philadelphia 76ers': '식서즈',
  'Phoenix Suns': '선즈',
  'Golden State Warriors': '워리어스',
  'Los Angeles Clippers': '클리퍼스',
  'LA Clippers': '클리퍼스',
  'Miami Heat': '히트',
  'Dallas Mavericks': '매버릭스',
  'New York Knicks': '닉스',
  'Cleveland Cavaliers': '캐벌리어스',
  'Sacramento Kings': '킹스',
  'Memphis Grizzlies': '그리즐리스',
  'New Orleans Pelicans': '펠리컨스',
  'Minnesota Timberwolves': '팀버울브스',
  'Oklahoma City Thunder': '선더',
  'Portland Trail Blazers': '포틀랜드',
  'Toronto Raptors': '랩터스',
  'San Antonio Spurs': '스퍼스',
  'Utah Jazz': '재즈',
  'Chicago Bulls': '불스',
  'Atlanta Hawks': '호크스',
  'Washington Wizards': '위저즈',
  'Orlando Magic': '매직',
  'Detroit Pistons': '피스톤스',
  'Indiana Pacers': '페이서스',
  'Brooklyn Nets': '넷츠',
  'Charlotte Hornets': '호넷츠',
  'Houston Rockets': '로켓츠',

  // ─── NHL ───
  'Anaheim Ducks': '애너하임',
  'Arizona Coyotes': '애리조나',
  'Boston Bruins': '보스턴B',
  'Buffalo Sabres': '버팔로',
  'Calgary Flames': '캘거리',
  'Carolina Hurricanes': '캐롤라이나',
  'Chicago Blackhawks': '블랙호크스',
  'Colorado Avalanche': '콜로라도A',
  'Columbus Blue Jackets': '콜럼버스BJ',
  'Dallas Stars': '댈러스S',
  'Detroit Red Wings': '디트로이트RW',
  'Edmonton Oilers': '에드먼턴',
  'Florida Panthers': '플로리다P',
  'Los Angeles Kings': 'LA킹스',
  'Minnesota Wild': '미네소타W',
  'Montreal Canadiens': '몬트리올C',
  'Nashville Predators': '내슈빌P',
  'New Jersey Devils': '뉴저지',
  'New York Islanders': 'NY아일랜더스',
  'New York Rangers': 'NY레인저스',
  'Ottawa Senators': '오타와',
  'Philadelphia Flyers': '필라델피아F',
  'Pittsburgh Penguins': '피츠버그',
  'San Jose Sharks': '산호세',
  'Seattle Kraken': '시애틀K',
  'St. Louis Blues': '세인트루이스B',
  'Tampa Bay Lightning': '탬파베이',
  'Toronto Maple Leafs': '토론토ML',
  'Utah Mammoth': '유타매머스',
  'Vancouver Canucks': '밴쿠버C',
  'Vegas Golden Knights': '베가스',
  'Washington Capitals': '워싱턴C',
  'Winnipeg Jets': '위니펙',

  // ─── MLB ───
  'Arizona Diamondbacks': '다이아몬드백스',
  'Atlanta Braves': '브레이브스',
  'Baltimore Orioles': '오리올스',
  'Boston Red Sox': '레드삭스',
  'Chicago Cubs': '컵스',
  'Chicago White Sox': '화이트삭스',
  'Cincinnati Reds': '레즈',
  'Cleveland Guardians': '가디언스',
  'Colorado Rockies': '로키스',
  'Detroit Tigers': '타이거즈',
  'Houston Astros': '애스트로스',
  'Kansas City Royals': '로열스',
  'Los Angeles Angels': '에인절스',
  'Los Angeles Dodgers': '다저스',
  'Miami Marlins': '말린스',
  'Milwaukee Brewers': '브루어스',
  'Minnesota Twins': '트윈스',
  'New York Mets': '메츠',
  'New York Yankees': '양키스',
  'Athletics': '애슬레틱스',
  'Oakland Athletics': '애슬레틱스',
  'Philadelphia Phillies': '필리스',
  'Pittsburgh Pirates': '파이어리츠',
  'San Diego Padres': '파드리스',
  'San Francisco Giants': '자이언츠',
  'Seattle Mariners': '매리너스',
  'St. Louis Cardinals': '카디널스',
  'Tampa Bay Rays': '레이스',
  'Texas Rangers': '텍사스R',
  'Toronto Blue Jays': '블루제이스',
  'Washington Nationals': '내셔널스',

  // ─── KBO ───
  'Samsung Lions': '삼성라이온즈',
  'Doosan Bears': '두산베어스',
  'LG Twins': 'LG트윈스',
  'KT Wiz': 'KT위즈',
  'Kia Tigers': 'KIA타이거즈',
  'NC Dinos': 'NC다이노스',
  'SSG Landers': 'SSG랜더스',
  'Lotte Giants': '롯데자이언츠',
  'Hanwha Eagles': '한화이글스',
  'Kiwoom Heroes': '키움히어로즈',

  // ─── NPB ───
  'Chiba Lotte Marines': '지바롯데',
  'Saitama Seibu Lions': '사이타마세이부',
  'Yomiuri Giants': '요미우리',
  'Hanshin Tigers': '한신타이거즈',
  'Hiroshima Toyo Carp': '히로시마',
  'Yokohama DeNA BayStars': '요코하마DeNA',
  'Tokyo Yakult Swallows': '도쿄야쿠르트',
  'Chunichi Dragons': '주니치',
  'Orix Buffaloes': '오릭스',
  'Fukuoka SoftBank Hawks': '후쿠오카소프트뱅크',
  'Hokkaido Nippon-Ham Fighters': '니혼햄',
  'Tohoku Rakuten Golden Eagles': '라쿠텐',

  // ─── KBL ───
  'Seoul Samsung Thunders': '서울삼성',
  'Anyang KGC': '안양정관',
  'Wonju DB Promy': '원주DB',
  'Seoul SK Knights': '서울SK',
  'Goyang Carrot Jumpers': '고양캐롯',
  'Busan KCC Egis': '부산KCC',
  'Changwon LG Sakers': '창원LG',
  'Daegu KOGAS Pegasus': '대구한국가스공사',
  'Suwon KT Sonicboom': '수원KT',
  'Ulsan Hyundai Mobis Phoebus': '울산현대모비스',

  // ─── Euroleague Basketball ───
  'ASVEL Lyon-Villeurbanne': 'ASVEL리옹',
  'Anadolu Efes SK': '아나돌루에페스',
  'BC Olympiakos Piraeus': '올림피아코스BC',
  'BC Zalgiris Kaunas': '잘기리스',
  'Baskonia Vitoria-Gasteiz': '바스코니아',
  'Dubai Basketball': '두바이BC',
  'Paris Basketball': '파리BC',
  'Valencia Basket': '발렌시아BC',
  'Real Madrid Baloncesto': '레알마드리드BC',
  'FC Barcelona Basquet': '바르셀로나BC',
  'Maccabi Tel Aviv': '마카비텔아비브',
  'Partizan Belgrade': '파르티잔',
  'Crvena Zvezda': '츠르베나즈베즈다',
  'Fenerbahce Beko': '페네르바체BC',
  'Virtus Bologna': '비르투스볼로냐',
  'Olimpia Milano': '올림피아밀라노',

  // ─── A-League ───
  'Adelaide United': '애들레이드',
  'Wellington Phoenix': '웰링턴',
  'Melbourne City FC': '멜번시티',
  'Melbourne Victory': '멜번빅토리',
  'Sydney FC': '시드니FC',
  'Western United': '웨스턴유나이티드',
  'Central Coast Mariners': '센트럴코스트',
  'Brisbane Roar': '브리즈번',
  'Perth Glory': '퍼스글로리',
  'Macarthur FC': '맥아서FC',
  'Western Sydney Wanderers': '웨스턴시드니',
  'Newcastle Jets': '뉴캐슬제츠',
  'Auckland FC': '오클FC',

  // ─── Eredivisie ───
  'Heracles Almelo': '헤라클레스',
  'FC Utrecht': '위트레흐트',
  'AZ Alkmaar': '알크마르',
  'AZ': '알크마르',
  'FC Twente': '트벤테',
  'FC Groningen': '흐로닝언',
  'NEC Nijmegen': '네이메헌',
  'NEC': '네이메헌',
  'Sparta Rotterdam': '스파르타R',
  'SC Heerenveen': '헤이렌베인',
  'PEC Zwolle': '즈볼러',
  'Fortuna Sittard': '포르투나S',
  'Go Ahead Eagles': '고어헤드',
  'Excelsior': '엑셀시오르',
  'FC Volendam': '폴렌담',
  'NAC Breda': '브레다',
  'Telstar': '텔스타',
  'Willem II': '빌렘II',
  'RKC Waalwijk': 'RKC발비크',
  'FC Emmen': '에먼',
  'SC Cambuur': '캄뷔르',
  'Den Helder Suns': '덴헬더선스',
  'Donar Groningen': '도나르흐로닝언',

  // ─── EFL Championship ───
  'Norwich City': '노리치',
  'Norwich City FC': '노리치',
  'Wrexham': '렉섬',
  'Wrexham AFC': '렉섬',
  'Middlesbrough': '미들즈브러',
  'Middlesbrough FC': '미들즈브러',
  'Millwall': '밀월',
  'Millwall FC': '밀월',
  'Birmingham City': '버밍엄',
  'Bristol City': '브리스톨',
  'Blackburn Rovers': '블랙번',
  'Sheffield Wednesday': '셰필드웬',
  'Swansea City': '스완지',
  'Stoke City': '스토크',
  'Oxford United': '옥스퍼드',
  'Watford': '왓포드',
  'Watford FC': '왓포드',
  'West Bromwich Albion': '웨스트브롬',
  'Charlton Athletic': '찰턴',
  'Coventry City': '코번트리',
  'Queens Park Rangers': '퀸즈파크',
  'Preston North End': '프레스턴',
  'Hull City': '헐시티',
  'Derby County': '더비카운티',
  'Portsmouth': '포츠머스',
  'Portsmouth FC': '포츠머스',
  'Plymouth Argyle': '플리머스',
  'Cardiff City': '카디프',
  'Sunderland FC': '선덜랜드',

  // ─── MLS ───
  'Nashville SC': '내슈빌SC',
  'New York Red Bulls': '뉴욕레드불스',
  'New York City FC': '뉴욕시티FC',
  'New England Revolution': '뉴잉글랜드',
  'Real Salt Lake': '레알솔트레이크',
  'Minnesota United': '미네소타유나이티드',
  'Vancouver Whitecaps': '밴쿠버',
  'San Jose Earthquakes': '새너제이',
  'San Diego FC': '샌디에고FC',
  'Charlotte FC': '샬럿FC',
  'St. Louis City SC': '세인트루이스',
  'Seattle Sounders': '시애틀',
  'Seattle Sounders FC': '시애틀',
  'Chicago Fire': '시카고파이어',
  'Chicago Fire FC': '시카고파이어',
  'Atlanta United': '애틀랜타유나이티드',
  'Atlanta United FC': '애틀랜타유나이티드',
  'Austin FC': '오스틴FC',
  'Orlando City': '올랜도시티',
  'Orlando City SC': '올랜도시티',
  'Inter Miami': '인터마이애미',
  'Inter Miami CF': '인터마이애미',
  'Columbus Crew': '콜럼버스',
  'Colorado Rapids': '콜로라도',
  'Toronto FC': '토론토FC',
  'Portland Timbers': '포틀랜드팀버스',
  'Philadelphia Union': '필라델피아유니온',
  'Houston Dynamo': '휴스턴다이나모',
  'Houston Dynamo FC': '휴스턴다이나모',
  'CF Montreal': '몬트리올',
  'CF Montréal': '몬트리올',
  'DC United': 'DC유나이티드',
  'D.C. United': 'DC유나이티드',
  'FC Dallas': 'FC댈러스',
  'FC Cincinnati': 'FC신시내티',
  'LA Galaxy': 'LA갤럭시',
  'Los Angeles FC': 'LAFC',
  'Sporting Kansas City': '스포르팅KC',

  // ─── K-League ───
  'FC Seoul': 'FC서울',
  'Jeonbuk Hyundai Motors': '전북현대',
  'Ulsan Hyundai': '울산현대',
  'Suwon Samsung Bluewings': '수원삼성',
  'Pohang Steelers': '포항스틸러스',
  'Daegu FC': '대구FC',
  'Gangwon FC': '강원FC',
  'Incheon United': '인천유나이티드',
  'Jeju United': '제주유나이티드',
  'Gwangju FC': '광주FC',
  'Suwon FC': '수원FC',
  'Gimcheon Sangmu': '김천상무',
  'Daejeon Hana Citizen': '대전하나',
  'Jeonnam Dragons': '전남드래곤즈',
  'Seoul E-Land': '서울이랜드',
  'Busan IPark': '부산아이파크',
  'Ansan Greeners': '안산그리너스',
  'Chungnam Asan': '충남아산',
  'Gimpo FC': '김포FC',

  // ─── KOVO (Korean Volleyball) ───
  'Samsung Fire & Marine': '삼성화재',
  'Korean Air': '대한항공',
  'Woori Card': '우리카드',
  'KB Insurance': 'KB손보',
  'OK Savings Bank': 'OK저축',
  'Pepper Savings Bank': '페퍼저축',
  'Hyundai Capital': '현대캐피탈',
  'IBK Altos': 'IBK기업',
  'GS Caltex': 'GS칼텍스',
  'Heungkuk Life': '흥국생명',
  'Korea Expressway': '도로공사',
  'Hyundai E&C': '현대건설',
  'Daejeon JungKwanJang': '대전정관',
  'KEPCO': '한국전력',

  // ─── Scottish Premiership ───
  'Heart of Midlothian': '하츠',
  'Hearts': '하츠',
  'Hibernian': '히버니안',
  'Aberdeen': '애버딘',
  'Aberdeen FC': '애버딘',
  'Dundee United': '던디유나이티드',
  'Dundee FC': '던디',
  'Kilmarnock': '킬마녹',
  'Motherwell': '마더웰',
  'St Mirren': '세인트미렌',
  'Ross County': '로스카운티',
  'St Johnstone': '세인트존스턴',
  'Livingston': '리빙스턴',

  // ─── Turkish Super Lig ───
  'Trabzonspor': '트라브존스포르',
  'Istanbul Basaksehir': '바샥셰히르',
  'Antalyaspor': '안탈리아스포르',
  'Alanyaspor': '알라냐스포르',
  'Konyaspor': '코냐스포르',
  'Sivasspor': '시바스스포르',
  'Kasimpasa': '카심파사',
  'Hatayspor': '하타이스포르',
  'Kayserispor': '카이세리스포르',
  'Gaziantep FK': '가지안텝',
  'Adana Demirspor': '아다나',
  'Rizespor': '리제스포르',
  'Samsunspor': '삼순스포르',
  'Pendikspor': '펜디크스포르',
  'Eyupspor': '에윕스포르',
  'Bodrumspor': '보드룸스포르',
  'Goztepe': '괴즈테페',
};

/**
 * 영어 팀 이름을 한국어로 변환.
 * 1차: 정확한 매핑 조회
 * 2차: "FC", "SC", "CF" 등 접미/접두사 제거 후 재시도
 */
export function getKoreanTeamName(englishName: string): string {
  if (!englishName) return englishName;

  // 1. Direct lookup
  const direct = ENGLISH_TO_KOREAN[englishName];
  if (direct) return direct;

  // 2. Strip common suffixes/prefixes and retry
  const stripped = englishName
    .replace(/\s+(FC|SC|CF|AC|BC|AFC|SFC|BK|FK|SK|IF|FF|SV|SE)$/i, '')
    .replace(/^(FC|SC|CF|AC|BC|AFC|SFC|BK|FK|SK|IF|FF|SV|SE)\s+/i, '')
    .trim();
  if (stripped !== englishName) {
    const match = ENGLISH_TO_KOREAN[stripped];
    if (match) return match;
  }

  return englishName;
}
